name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sef_efakture
        options: >-
          --health-cmd "pg_isready -U postgres" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma Client
        run: npm run db:generate --workspace=backend
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/sef_efakture?schema=public
      - name: Apply migrations
        run: npm run migrate:deploy --workspace=backend
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/sef_efakture?schema=public
      - name: Seed database
        run: npm run db:seed --workspace=backend
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/sef_efakture?schema=public
      - name: Run tests
        run: npm run test --workspace=backend
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://postgres:password@localhost:5432/sef_efakture?schema=public
